site_name: 은중 스터디
site_description: 자료 포털 (Materials Hub)
# site_url: https://<username>.github.io/<repo>/
# repo_url: https://github.com/<username>/<repo>

theme:
  name: material
  language: ko
  features:
    - navigation.top
    - navigation.sections
    - toc.integrate
    - content.code.copy
  # logo: assets/images/logo.png
  # favicon: assets/images/logo.png

nav:
  - 홈(Home): index.md
  - OT: ot.md
  - Week 1:
      - Overview: week1.md
  

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
