backend:
  name: github
  repo: EJEJejie/ejfactory.github.io
  base_url: https://netlify-cms-github-oauth-provider-64dz.onrender.com  # Render OAuth 주소
  auth_endpoint: auth
  branch: main

site_url: https://ejejejie.github.io/ejfactory.github.io
public_folder: "/images/uploads"
media_folder: "docs/static/images/uploads"


collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "docs/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Week 1"
        name: "week1"
        file: "docs/week1.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Week 2"
        name: "week2"
        file: "docs/week2.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
