backend:
  name: github
  repo: EJEJejie/ejfactory.github.io
  branch: main
  base_url: https://netlify-cms-github-oauth-provider-64dz.onrender.com  # ← Render 배포 URL 입력
  auth_endpoint: auth                                                # ← 그대로 복사

media_folder: "docs/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "docs/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Week 1"
        name: "week1"
        file: "docs/week1.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Week 2"
        name: "week2"
        file: "docs/week2.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
